[window]
# decorations = "None"
decorations = "Full"
[font]
# requires JetBrainsMonoNerdFont
# MacOS: brew install --cask font-jetbrains-mono-nerd-font
# normal = { family = "DejaVuSansMNerdFont" }
# normal = { family = "HackNerdFont" }
# normal = { family = "JetBrainsMonoNerdFont" }
normal = { family = "JetBrainsMono Nerd Font Mono", style = "ExtraLight" }
# size = 10.25
size = 13
offset = { y = 1 }
# glyph_offset = { x = 1, y = -2 }
[colors]
# primary = { background = "#000000" }
[mouse]
hide_when_typing = true
bindings = [
             { mouse = "Middle", mods = "None", action = "PasteSelection" },
           ]
[keyboard]
bindings = [
             { key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
             # completely disable Ctrl+Insert keybinding to reach tty (only copies selected text to clipboard)
             # { key = "Insert", mods = "Control", chars = "\u001b[2;5~" },
             # { key = "Insert", mods = "Control", action = "None" },
             { key = "Insert", mods = "Control", action = "Copy" },
             { key = "Insert", mods = "Shift", action = "Paste" },
             { key = "ContextMenu", mods = "None", action = "ResetFontSize" },
             { key = "-", mods = "Control", chars = "\u001f" },
             { key = "=", mods = "Control", chars = "=" },  # could be bound to something else
             { key = "_", mods = "Control|Shift", action = "DecreaseFontSize" },
             { key = "+", mods = "Control|Shift", action = "IncreaseFontSize" },
             { key = "NumpadSubtract", mods = "Control", chars = "" },  # somehow triggers regular Ctrl-- (bug?)
             { key = "NumpadAdd", mods = "Control", chars = "+" },  # could be bound to something else
             { key = "NumpadSubtract", mods = "Control|Shift", action = "DecreaseFontSize" },
             { key = "NumpadAdd", mods = "Control|Shift", action = "IncreaseFontSize" },
           ]
