[window]
decorations = "None"
[font]
# normal = { family = "DejaVuSansMNerdFont" }
# normal = { family = "HackNerdFont" }
normal = { family = "JetBrainsMonoNerdFont" }
# size = 10.25
offset = { y = -2 }
# glyph_offset = { x = 1, y = -2 }
size = 10
[colors]
# primary = { background = "#000000" }
[keyboard]
# completely disable Ctrl+Insert keybinding to reach tty (only copies selected text to clipboard)
bindings = [
             { key = "Insert", mods = "Control", action = "None" },
             { key = "ContextMenu", mods = "None", action = "ResetFontSize" },
             { key = "-", mods = "Control", action = "None" },
             { key = "=", mods = "Control", action = "None" },
             { key = "_", mods = "Control|Shift", action = "DecreaseFontSize" },
             { key = "+", mods = "Control|Shift", action = "IncreaseFontSize" },
             { key = "NumpadSubtract", mods = "Control", action = "None" },
             { key = "NumpadAdd", mods = "Control", action = "None" },
             { key = "NumpadSubtract", mods = "Control|Shift", action = "DecreaseFontSize" },
             { key = "NumpadAdd", mods = "Control|Shift", action = "IncreaseFontSize" },
           ]
