# Alacritty config is in ~\AppData\Roaming\alacritty\alacritty.toml

# SSH setup
# create host aliases in ~\.ssh\config:
# vim $env:USERPROFILE\.ssh\config
# run keygen to create private/public key pair
# ssh-keygen.exe
# copy the public key to the remote machine (ssh-copy-id equivalent in PowerShell):
# type $env:USERPROFILE\.ssh\id_ed25519.pub | ssh devpc "mkdir -p ~/.ssh && cat >> ~/.ssh/authorized_keys"

[window]
# decorations = "None"
decorations = "Full"
[font]
# normal = { family = "DejaVuSansMNerdFont" }
# normal = { family = "HackNerdFont" }
# normal = { family = "JetBrainsMonoNerdFont" }
# normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
normal = { family = "JetBrainsMono Nerd Font Mono" }
# size = 10.25
size = 12
offset = { y = 1 }
# glyph_offset = { x = 1, y = -2 }
[colors]
# primary = { background = "#000000" }
[mouse]
hide_when_typing = true
bindings = [
             { mouse = "Middle", mods = "None", action = "PasteSelection" },
           ]
[keyboard]
bindings = [
             # by default Windows 10 swallows Ctrl+/ binding, this remaps it earlier in Alacritty
             { key = "/", mods = "Control", chars = "\u001f" },
             { key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
             # completely disable Ctrl+Insert keybinding to reach tty (only copies selected text to clipboard)
             { key = "Insert", mods = "Control", action = "Copy" },
             { key = "Insert", mods = "Shift", action = "Paste" },
             { key = "ContextMenu", mods = "None", action = "ResetFontSize" },
             { key = "-", mods = "Control", chars = "\u001f" },
             { key = "=", mods = "Control", chars = "=" },  # could be bound to something else
             { key = "_", mods = "Control|Shift", action = "DecreaseFontSize" },
             { key = "+", mods = "Control|Shift", action = "IncreaseFontSize" },
             { key = "NumpadSubtract", mods = "Control", chars = "" },  # somehow triggers regular Ctrl-- (bug?)
             { key = "NumpadAdd", mods = "Control", chars = "+" },  # could be bound to something else
             { key = "NumpadSubtract", mods = "Control|Shift", action = "DecreaseFontSize" },
             { key = "NumpadAdd", mods = "Control|Shift", action = "IncreaseFontSize" },
           ]
